# A generic, single database configuration for Alembic.

[alembic]
# Path to migration scripts
script_location = app/db/migrations

# Template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# Sys.path configuration
prepend_sys_path = .

# Timezone to use when rendering dates in migration comments
timezone = UTC

# Max length of characters to apply to the "slug" field
truncate_slug_length = 40

# Set to 'true' to run the environment during the 'revision' command
revision_environment = false

# Set to 'true' to allow .pyc and .pyo files without .py
sourceless = false

# Version table name
version_table = alembic_version

# Version table schema
# version_table_schema = None

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
