"""Kairo Autonomous Causal Explanation, Event Chain Reconstruction & "Why Did This Happen?" Engine (Task 112)."""

from app.causal.explanation.domain import (
    CausalAlternative,
    CausalConfidenceBreakdown,
    CausalContributor,
    CausalExplanation,
    CausalLink,
    CausalRelationshipRole,
    CausalStatus,
    CounterfactualScenario,
    EventChain,
    EventChainStep,
    EvidenceClassification,
    ExplanationEvidence,
    ExplanationGap,
    ExplanationLifecycleStage,
    ExplanationQualityAssessment,
    ExplanationRequest,
    ExplanationVerification,
    RootCauseCategory,
    VerificationOutcome,
    gen_explanation_id,
    utc_now,
)

__all__ = [
    "CausalAlternative",
    "CausalConfidenceBreakdown",
    "CausalContributor",
    "CausalExplanation",
    "CausalLink",
    "CausalRelationshipRole",
    "CausalStatus",
    "CounterfactualScenario",
    "EventChain",
    "EventChainStep",
    "EvidenceClassification",
    "ExplanationEvidence",
    "ExplanationGap",
    "ExplanationLifecycleStage",
    "ExplanationQualityAssessment",
    "ExplanationRequest",
    "ExplanationVerification",
    "RootCauseCategory",
    "VerificationOutcome",
    "gen_explanation_id",
    "utc_now",
]
