"""Tests for SkillRegistry, SemVer validation, dependency cycle detection, and manifest rules."""

import pytest
from app.skills.catalog import create_default_skills
from app.skills.registry import SkillRegistry
from app.skills.schemas import (
    SkillCategory,
    SkillHealthStatus,
    SkillManifest,
    SkillRiskLevel,
    SkillSource,
)


@pytest.fixture
def empty_registry() -> SkillRegistry:
    """Provide a fresh empty registry for isolated testing."""
    return SkillRegistry()


@pytest.fixture
def populated_registry() -> SkillRegistry:
    """Provide registry populated with canonical built-in skills."""
    reg = SkillRegistry()
    for skill in create_default_skills():
        reg.register(skill)
    return reg


def test_registry_register_and_lookup(empty_registry: SkillRegistry) -> None:
    """Ensure valid trusted skill registers and can be retrieved."""
    manifest = SkillManifest(
        id="test.sample",
        name="Sample Test Skill",
        description="A sample skill for testing registry behavior.",
        version="1.0.0",
        category=SkillCategory.RESEARCH,
        risk_level=SkillRiskLevel.READ_ONLY,
        required_tools=["web_search"],
        required_permissions=["web.read"],
        source=SkillSource.BUILTIN,
    )
    empty_registry.register(manifest)

    retrieved = empty_registry.get("test.sample")
    assert retrieved is not None
    assert retrieved.name == "Sample Test Skill"
    assert retrieved.version == "1.0.0"
    assert retrieved.enabled is True


def test_registry_rejects_duplicate_registration(empty_registry: SkillRegistry) -> None:
    """Ensure duplicate skill IDs cannot be registered."""
    manifest = SkillManifest(
        id="test.duplicate",
        name="Duplicate Skill",
        description="Testing duplicate collision.",
        version="1.0.0",
        category=SkillCategory.RESEARCH,
        risk_level=SkillRiskLevel.READ_ONLY,
        source=SkillSource.BUILTIN,
    )
    empty_registry.register(manifest)

    with pytest.raises(ValueError) as exc:
        empty_registry.register(manifest)
    assert "already registered" in str(exc.value)


def test_registry_rejects_invalid_semver(empty_registry: SkillRegistry) -> None:
    """Ensure non-SemVer versions are rejected."""
    with pytest.raises(ValueError) as exc:
        SkillManifest(
            id="test.badver",
            name="Bad Version Skill",
            description="Testing invalid version.",
            version="v1-final",  # Not valid MAJOR.MINOR.PATCH
            category=SkillCategory.RESEARCH,
            risk_level=SkillRiskLevel.READ_ONLY,
            source=SkillSource.BUILTIN,
        )
    assert "SemVer" in str(exc.value) or "version" in str(exc.value)


def test_registry_rejects_invalid_id_format() -> None:
    """Ensure skill IDs must follow namespaced format (e.g. category.name)."""
    with pytest.raises(ValueError) as exc:
        SkillManifest(
            id="Invalid Name With Spaces",
            name="Invalid ID Skill",
            description="Testing invalid ID.",
            version="1.0.0",
            category=SkillCategory.RESEARCH,
            risk_level=SkillRiskLevel.READ_ONLY,
            source=SkillSource.BUILTIN,
        )
    assert "namespace" in str(exc.value) or "id" in str(exc.value)


def test_registry_rejects_untrusted_model_skills(empty_registry: SkillRegistry) -> None:
    """Ensure model-generated/untrusted skill manifests are rejected (Section 5 & 78)."""
    manifest = SkillManifest(
        id="model.untrusted",
        name="Model Generated Skill",
        description="Self-generated by LLM.",
        version="1.0.0",
        category=SkillCategory.DEVELOPER,
        risk_level=SkillRiskLevel.DESTRUCTIVE,
        source=SkillSource.MODEL_GENERATED,
    )
    with pytest.raises(PermissionError) as exc:
        empty_registry.register(manifest)
    assert "Model-generated" in str(exc.value) or "trusted" in str(exc.value)


def test_registry_detects_dependency_cycles(empty_registry: SkillRegistry) -> None:
    """Ensure dependency cycles between skills are rejected (Section 60)."""
    skill_a = SkillManifest(
        id="chain.a",
        name="Chain A",
        description="A depends on B",
        version="1.0.0",
        category=SkillCategory.RESEARCH,
        risk_level=SkillRiskLevel.READ_ONLY,
        dependencies=["chain.b"],
        source=SkillSource.BUILTIN,
    )
    skill_b = SkillManifest(
        id="chain.b",
        name="Chain B",
        description="B depends on A",
        version="1.0.0",
        category=SkillCategory.RESEARCH,
        risk_level=SkillRiskLevel.READ_ONLY,
        dependencies=["chain.a"],
        source=SkillSource.BUILTIN,
    )

    empty_registry.register(skill_a)
    with pytest.raises(ValueError) as exc:
        empty_registry.register(skill_b)
    assert "circular" in str(exc.value).lower() or "cycle" in str(exc.value).lower()


def test_registry_enable_and_disable(populated_registry: SkillRegistry) -> None:
    """Ensure skills can be enabled or disabled via backend governance."""
    skill_id = "computer.assist"
    assert populated_registry.is_enabled(skill_id) is False  # Disabled by default for safety

    # Enable
    updated = populated_registry.set_enabled(skill_id, True)
    assert updated.enabled is True
    assert populated_registry.is_enabled(skill_id) is True

    # Disable
    updated = populated_registry.set_enabled(skill_id, False)
    assert updated.enabled is False
    assert populated_registry.is_enabled(skill_id) is False


def test_registry_health_computation(populated_registry: SkillRegistry) -> None:
    """Ensure health status accurately reflects tool availability."""
    # When available_tools is empty, skills with required tools should be DEGRADED or UNAVAILABLE
    health = populated_registry.get_health("research.web", available_tools=set())
    assert health in (SkillHealthStatus.DEGRADED, SkillHealthStatus.UNAVAILABLE)

    # When all required tools are available, health should be HEALTHY
    skill = populated_registry.get("research.web")
    assert skill is not None
    health_ok = populated_registry.get_health("research.web", available_tools=set(skill.required_tools))
    assert health_ok == SkillHealthStatus.HEALTHY


def test_registry_lists_all_canonical_skills(populated_registry: SkillRegistry) -> None:
    """Verify all 11 built-in canonical skills are properly registered."""
    skills = populated_registry.list_skills()
    assert len(skills) >= 11
    ids = {s.id for s in skills}
    expected_ids = {
        "research.web",
        "knowledge.search",
        "documents.analyze",
        "developer.repository",
        "github.analysis",
        "project.analysis",
        "automation.manage",
        "browser.research",
        "voice.assist",
        "vision.analyze",
        "computer.assist",
    }
    assert expected_ids.issubset(ids)
