"""Plan model, PlanStatus, monotonic versioning, and scope lock for Kairo Cognitive Planning (Task 41)."""

from datetime import UTC, datetime
from enum import Enum
from typing import Any
import uuid
from pydantic import BaseModel, ConfigDict, Field

from app.cognition.steps import PlanStep, StepStatus


def utc_now() -> datetime:
    return datetime.now(UTC)


class PlanStatus(str, Enum):
    """Lifecycle states of a cognitive plan."""

    DRAFT = "DRAFT"
    READY = "READY"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    REPLANNING = "REPLANNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"


class PlanRiskLevel(str, Enum):
    """Overall plan risk evaluation."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ScopeLock(BaseModel):
    """Strict resource, environmental, and project perimeter for plan execution."""

    model_config = ConfigDict(extra="ignore")

    allowed_resources: list[str] = Field(default_factory=list)
    allowed_environments: list[str] = Field(default_factory=lambda: ["development"])
    project_id: str | None = Field(default=None)
    user_id: str = Field(..., description="Owner user ID")
    locked: bool = Field(default=True, description="When true, new resources require re-evaluation")


class PlanDiff(BaseModel):
    """Detailed structural diff between two plan versions."""

    model_config = ConfigDict(extra="ignore")

    old_plan_id: str
    new_plan_id: str
    old_version: int
    new_version: int
    added_steps: list[str] = Field(default_factory=list)
    removed_steps: list[str] = Field(default_factory=list)
    modified_steps: list[str] = Field(default_factory=list)
    changed_assumptions: list[str] = Field(default_factory=list)
    old_risk: str
    new_risk: str
    approval_required: bool = Field(default=False)


class Plan(BaseModel):
    """Authoritative structured plan generated by the cognitive engine."""

    model_config = ConfigDict(extra="ignore")

    plan_id: str = Field(default_factory=lambda: f"plan_{uuid.uuid4().hex[:12]}")
    goal_id: str = Field(..., description="Target goal ID")
    user_id: str = Field(..., description="Owner user ID")
    project_id: str | None = Field(default=None)
    version: int = Field(default=1, description="Monotonic version number")
    parent_plan_id: str | None = Field(default=None, description="Previous version or parent plan")
    status: PlanStatus = Field(default=PlanStatus.DRAFT)
    reasoning_mode: str = Field(default="DECOMPOSITION")
    steps: list[PlanStep] = Field(default_factory=list)
    dependencies: dict[str, list[str]] = Field(default_factory=dict, description="Step ID -> list of prerequisite Step IDs")
    assumptions: list[dict[str, Any]] = Field(default_factory=list)
    constraints: dict[str, Any] = Field(default_factory=dict)
    success_criteria: list[str] = Field(default_factory=list)
    risk: PlanRiskLevel = Field(default=PlanRiskLevel.LOW)
    scope_lock: ScopeLock
    cost_estimate: dict[str, Any] = Field(default_factory=dict)
    rationale: str | None = Field(default=None)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)

    def get_step(self, step_id: str) -> PlanStep | None:
        """Find a step by ID."""
        for s in self.steps:
            if s.step_id == step_id:
                return s
        return None

    def get_completed_steps(self) -> list[PlanStep]:
        """Return steps with COMPLETED status."""
        return [s for s in self.steps if s.status == StepStatus.COMPLETED]

    def get_ready_steps(self) -> list[PlanStep]:
        """Return steps whose dependencies are all completed and status is PENDING or READY."""
        completed_ids = {s.step_id for s in self.get_completed_steps()}
        ready = []
        for s in self.steps:
            if s.status in {StepStatus.PENDING, StepStatus.READY}:
                deps = set(s.dependencies)
                if deps.issubset(completed_ids):
                    ready.append(s)
        return ready

    def is_all_completed(self) -> bool:
        """Return true if every step is COMPLETED or SKIPPED."""
        if not self.steps:
            return False
        return all(s.status in {StepStatus.COMPLETED, StepStatus.SKIPPED} for s in self.steps)

    def supersede(self) -> None:
        """Mark this plan version as superseded by a new version."""
        self.status = PlanStatus.SUPERSEDED
        self.updated_at = utc_now()
