"""Claim Verification, Source Integrity & Evidence Provenance Engine (Task 116).

Architectural invariant:
SOURCE != DOCUMENT != OBSERVATION != EXTRACTED EVIDENCE != CLAIM != INTERPRETATION != INFERENCE != VERIFICATION != BELIEF != TRUTH != AUTHORIZATION.
Never fabricate certainty.
"""

from app.claim_verification.domain import (
    Claim,
    ClaimFragment,
    ClaimType,
    ContradictionRecord,
    ContradictionType,
    CorroborationGroup,
    CorroborationType,
    EvidenceArtifact,
    EvidenceQualityProfile,
    EvidenceTransformation,
    IndependenceAssessment,
    IntegrityCheck,
    NegativeEvidenceType,
    ProvenanceLink,
    ProvenancePredicate,
    ReproductionAttempt,
    ReproducibilityStatus,
    Source,
    SourceCategory,
    SourceRelationship,
    SourceRelationshipType,
    SourceSnapshot,
    SourceTrustProfile,
    VerificationCase,
    VerificationCaseStatus,
    VerificationEvent,
    VerificationGap,
    VerificationMethod,
    VerificationMethodType,
    VerificationResult,
    VerificationSnapshot,
)

__all__ = [
    "Claim",
    "ClaimFragment",
    "ClaimType",
    "ContradictionRecord",
    "ContradictionType",
    "CorroborationGroup",
    "CorroborationType",
    "EvidenceArtifact",
    "EvidenceQualityProfile",
    "EvidenceTransformation",
    "IndependenceAssessment",
    "IntegrityCheck",
    "NegativeEvidenceType",
    "ProvenanceLink",
    "ProvenancePredicate",
    "ReproductionAttempt",
    "ReproducibilityStatus",
    "Source",
    "SourceCategory",
    "SourceRelationship",
    "SourceRelationshipType",
    "SourceSnapshot",
    "SourceTrustProfile",
    "VerificationCase",
    "VerificationCaseStatus",
    "VerificationEvent",
    "VerificationGap",
    "VerificationMethod",
    "VerificationMethodType",
    "VerificationResult",
    "VerificationSnapshot",
]
